version: '3.8'

services:
  php:
    image: php:8.0-apache
    container_name: php
    ports:
      - "8081:80"
    volumes:
      - ./websites/as1/public:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Student1
      MYSQL_DATABASE: assignment1
      MYSQL_USER: root
      MYSQL_PASSWORD: Student1
    volumes:
      - /Applications/XAMPP/xamppfiles/htdocs/as1/mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
